#pragma once
#include"../include/cmd_console_tools.h"
//坐标
////GAMEBOARD
#define GAMEBOARD_X 3
#define GAMEBOARD_Y 1
////SCOREBOARD
#define SCOREBOARD_X (GAMEBOARD_X+GAMEBOARD_WIDTH+10)
#define SCOREBOARD_Y GAMEBOARD_Y
#define SCOREBOARD_INFO_X (SCOREBOARD_X+SCOREBOARD_SIDE_WIDTH)
#define SCOREBOARD_INFO_Y (SCOREBOARD_Y+2)
////PROMPT
#define PROMPT_X 0
#define PROMPT_Y (CONSOLE_HEIGHT-4)



//大小
////GAMEBOARD
#define GAMEBOARD_WIDTH (26*BLOCK_WIDTH+2*GAMEBOARD_SIDE_WIDTH)
#define GAMEBOARD_HEIGHT (21*BLOCK_HEIGHT+2)
#define GAMEBOARD_SHADOW_WIDTH 1
#define GAMEBOARD_SIDE_WIDTH 2
////SCOREBOARD
#define SCOREBOARD_WIDTH 24
#define SCOREBOARD_HEIGHT 9
#define SCOREBOARD_SHADOW_WIDTH 1
#define SCOREBOARD_SIDE_WIDTH 2
#define SCOREBOARD_INFO_INTERVAL 2
#define SCOREBOARD_INFO_LENGTH 4
////CONSOLE
#define CONSOLE_WIDTH (GAMEBOARD_WIDTH+SCOREBOARD_WIDTH+23)
#define CONSOLE_HEIGHT (GAMEBOARD_HEIGHT+GAMEBOARD_Y+8)
#define CONSOLE_BUFFER_WIDTH CONSOLE_WIDTH
#define CONSOLE_BUFFER_HEIGHT CONSOLE_HEIGHT
#define CONSOLE_FONT_SIZE 18
////BLOCK
#define BLOCK_WIDTH 6
#define BLOCK_HEIGHT 3
////MENU
#define MENU_LIST_LENGTH 6

//颜色
////GAMEBOARD
#define GAMEBOARD_COLOR COLOR_WHITE 
#define GAMEBOARD_SIDE_COLOR COLOR_BLACK
#define GAMEBOARD_SHADOW_COLOR COLOR_BLUE
////SCOREBOARD
#define SCOREBOARD_COLOR COLOR_HBLACK
#define SCOREBOARD_SIDE_COLOR COLOR_WHITE
#define SCOREBOARD_SHADOW_COLOR COLOR_CYAN
#define SCOREBOARD_INFO_COLOR COLOR_BLACK

//文字
#define CONSOLE_FONT_FAMILY "点阵字体"
#define MENU_LIST {"打印边框和得分板","单个数字下落","单个数字下落时可平移和加速下落","单个数字下落时可进行所有操作","两个数字下落,可叠加","完整版"}
#define QUIT_KEY "Q"
#define SCOREBOARD_INFO_LIST {"下一个数字:","当前得分:","当前速度:","已消除行数:"}
